description = "프로젝트 규칙에 따라 커밋을 생성합니다."

prompt = """
# 커밋 생성

프로젝트의 커밋 규칙에 따라 현재 변경사항에 대한 커밋을 생성합니다.

## 사용자 입력
이슈 번호: {{args}}

## 커밋 규칙

**형식**: `type: 설명 #Issue_Number` 또는 `type: 설명 - 세부사항(필요 시) #Issue_Number`

**사용 가능한 타입**:
- `feat`: 새로운 기능 추가
- `fix`: 버그 수정
- `design`: CSS 등 사용자 UI 디자인 변경
- `docs`: 문서 변경 (README, 가이드, 주석 등)
- `chore`: 빌드 설정, 의존성, 환경 설정 변경
- `refactor`: 코드 리팩토링 혹은 성능 개선
- `test`: 테스트 코드 추가 또는 수정
- `comment`: 필요한 주석 추가 및 수정
- `style`: 코드 포맷팅, 세미콜론 등 (기능 변경 없음)
- `remove`: 파일, 기능, 의존성 제거
- `ci`: CI 설정 변경
- `cd`: CD 설정 변경

## 컨텍스트

Git 상태:
!{git status}

변경사항:
!{git diff HEAD}

최근 커밋:
!{git log --oneline -10}

## 지침

변경사항을 분석하고 적절한 커밋 메시지를 생성하세요. 모든 응답과 작업은 한국어로 진행해야 합니다.
"""