# File: .gemini/commands/commit.toml
description = "Create commit following project conventions"

prompt = """
# Create Commit

Create a commit for current changes following project commit conventions.

## User Input
Issue Number: {{args}}

## Commit Conventions

**형식**: `type: 설명 #Issue_Number` 또는 `type: 설명 - 세부사항(필요 시) #Issue_Number`

**사용 가능한 타입**:
- `feat`: 새로운 기능 추가
- `fix`: 버그 수정
- `design`: CSS 등 사용자 UI 디자인 변경
- `docs`: 문서 변경 (README, 가이드, 주석 등)
- `chore`: 빌드 설정, 의존성, 환경 설정 변경
- `refactor`: 코드 리팩토링 혹은 성능 개선
- `test`: 테스트 코드 추가 또는 수정
- `comment`: 필요한 주석 추가 및 수정
- `style`: 코드 포맷팅, 세미콜론 등 (기능 변경 없음)
- `remove`: 파일, 기능, 의존성 제거
- `ci`: CI 설정 변경
- `cd`: CD 설정 변경

## Context

Git Status:
!{git status}

Changes:
!{git diff HEAD}

Recent Commits:
!{git log --oneline -10}

## Instructions

Analyze changes and create appropriate commit message. Respond and work in Korean.
"""
