description = "프로젝트 템플릿에 따라 PR(Pull Request)을 생성합니다."

prompt = """
# Pull Request 생성

현재 브랜치의 변경사항을 분석하고, 프로젝트 PR 템플릿에 따라 이슈 #{{args}}에 연결된 Pull Request를 생성합니다.

## 사용자 입력
이슈 번호: {{args}}

## 컨텍스트

PR 템플릿:
!{cat .github/PULL_REQUEST_TEMPLATE.md}

현재 브랜치:
!{git branch --show-current}

Git 상태:
!{git status}

변경사항:
!{git diff HEAD}

커밋 내역:
!{git log --oneline -10}

Main 브랜치와의 차이점:
!{git diff main...HEAD}

## 지침

프로젝트 PR 템플릿과 규칙을 따르세요. 모든 응답과 작업은 한국어로 진행해야 합니다.
"""
